networks:
  syncal:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:16.10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-syncal}
      POSTGRES_USER: ${POSTGRES_USER:-syncal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-syncalsecret}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - syncal
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-syncal}:${POSTGRES_PASSWORD:-syncalsecret}@postgres:5432/${POSTGRES_DB:-syncal}}
      NODE_ENV: development
      PORT: 3001
    ports:
      - "${PORT_API:-3001}:3001"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3001/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - syncal

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3001}
    ports:
      - "${PORT_WEB:-3000}:3000"
    networks:
      - syncal

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER:-syncal}:${POSTGRES_PASSWORD:-syncalsecret}@postgres:5432/${POSTGRES_DB:-syncal}}
      NODE_ENV: development
    networks:
      - syncal
